Refactored all git hooks

diff --git a/git-hooks/pre-commit-csslint b/git-hooks/pre-commit-csslint
--- a/git-hooks/pre-commit-csslint
+++ b/git-hooks/pre-commit-csslint
@@ -1,38 +1,66 @@
-#!/usr/bin/php
-<?php
+#!/bin/bash
 
-$output = array();
-$return = 0;
-exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);
-$against = $return == 0 ? 'HEAD' : '4b825dc642cb6eb9a060e54bf8d69288fbee4904';
+##################################################################################
+# Override any of these in the config file
 
-exec("git diff-index --cached --name-only {$against}", $output);
+# Path to executable
+CL_BIN=/usr/local/bin/csslint
 
-$filename_pattern = '/\.css$/';
-$exit_status = 0;
+# Default file glob pattern
+CL_FILE_PATTERN="\.(css)$"
 
-foreach ($output as $file) 
-{
-	// Check file hasn't been moved or deleted
-	if (!file_exists($file)) continue;
+##################################################################################
 
-    // don't check files that aren't CSS
-    if (!preg_match($filename_pattern, $file)) continue;
+# parse config
+CONFIG_FILE=$(dirname $0)/config
+if [ -e $CONFIG_FILE ]; then
+	. $CONFIG_FILE
+fi
 
-	echo "Linting CSS file: $file\n";
+# simple check if executable is set up correctly
+if [ ! -x $CL_BIN ]; then
+	echo "Csslint bin not found or executable -> $CL_BIN"
+	exit 1
+fi
 
-    $lint_output = array();
-    exec("csslint " . escapeshellarg($file), $lint_output, $return);
+# stolen from template file
+if git rev-parse --verify HEAD
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
 
-    $output = implode("\n", $lint_output). "\n";
+# this is the magic: retrieve all files in staging area that
+# are added, modified or renamed but no deletions etc
+FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- )
 
-	echo $output;
+if [ "$FILES" == "" ]; then
+	exit 0
+fi
 
-	if (strpos($output, 'No errors')) {
-		continue;
-	}
+# match files against whitelist
+FILES_TO_CHECK=""
+for FILE in $FILES
+do
+	echo "$FILE" | egrep -q "$CL_FILE_PATTERN"
+	RETVAL=$?
+	if [ "$RETVAL" -eq "0" ]
+	then
+		FILES_TO_CHECK="$FILES_TO_CHECK $FILE"
+	fi
+done
 
-	$exit_status = 1;
-}
+if [ "$FILES_TO_CHECK" == "" ]; then
+	exit 0
+fi
 
-exit($exit_status);
+OUTPUT=$($CL_BIN $FILES_TO_CHECK)
+RETVAL=$?
+
+if [ $RETVAL -ne 0 ]; then
+	echo "$OUTPUT"
+fi
+
+exit $RETVAL
diff --git a/git-hooks/pre-commit-eslint b/git-hooks/pre-commit-eslint
--- a/git-hooks/pre-commit-eslint
+++ b/git-hooks/pre-commit-eslint
@@ -4,32 +4,32 @@
 # Override any of these in the config file
 
 # Path to executable
-YL_BIN=/usr/local/bin/yamllint
+ESL_BIN=/usr/local/bin/eslint
 
 # Default file glob pattern
-YL_FILE_PATTERN="\.(yml|yaml)$"
+ESL_FILE_PATTERN="\.(js|jsx)$"
 
 ##################################################################################
 
 # parse config
 CONFIG_FILE=$(dirname $0)/config
 if [ -e $CONFIG_FILE ]; then
-    . $CONFIG_FILE
+	. $CONFIG_FILE
 fi
 
 # simple check if executable is set up correctly
-if [ ! -x $YL_BIN ]; then
-    echo "Yamllint bin not found or executable -> $YL_BIN"
-    exit 1
+if [ ! -x $ESL_BIN ]; then
+	echo "Eslint bin not found or executable -> $ESL_BIN"
+	exit 1
 fi
 
 # stolen from template file
 if git rev-parse --verify HEAD
 then
-    against=HEAD
+	against=HEAD
 else
-    # Initial commit: diff against an empty tree object
-    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 # this is the magic: retrieve all files in staging area that
@@ -37,30 +37,30 @@ fi
 FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- )
 
 if [ "$FILES" == "" ]; then
-    exit 0
+	exit 0
 fi
 
 # match files against whitelist
 FILES_TO_CHECK=""
 for FILE in $FILES
 do
-    echo "$FILE" | egrep -q "$YL_FILE_PATTERN"
-    RETVAL=$?
-    if [ "$RETVAL" -eq "0" ]
-    then
-        FILES_TO_CHECK="$FILES_TO_CHECK $FILE"
-    fi
+	echo "$FILE" | egrep -q "$ESL_FILE_PATTERN"
+	RETVAL=$?
+	if [ "$RETVAL" -eq "0" ]
+	then
+		FILES_TO_CHECK="$FILES_TO_CHECK $FILE"
+	fi
 done
 
 if [ "$FILES_TO_CHECK" == "" ]; then
-    exit 0
+	exit 0
 fi
 
-OUTPUT=$($YL_BIN -s $FILES_TO_CHECK)
+OUTPUT=$($ESL_BIN $FILES_TO_CHECK)
 RETVAL=$?
 
 if [ $RETVAL -ne 0 ]; then
-    echo "$OUTPUT"
+	echo "$OUTPUT"
 fi
 
 exit $RETVAL
diff --git a/git-hooks/pre-commit-scss-lint b/git-hooks/pre-commit-scss-lint
--- a/git-hooks/pre-commit-scss-lint
+++ b/git-hooks/pre-commit-scss-lint
@@ -1,35 +1,66 @@
-#!/usr/bin/php
-<?php
+#!/bin/bash
 
-$output = array();
-$return = 0;
-exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);
-$against = $return == 0 ? 'HEAD' : '4b825dc642cb6eb9a060e54bf8d69288fbee4904';
+##################################################################################
+# Override any of these in the config file
 
-exec("git diff-index --cached --name-only {$against}", $output);
+# Path to executable
+SL_BIN=/usr/local/bin/scsslint
 
-$config = 'vendor/headsnet/build-tool-configs/scss-lint/.scss-lint.yml';
+# Default file glob pattern
+SL_FILE_PATTERN="\.(scss|sass)$"
 
-$filename_pattern = '/\.scss$/';
-$exit_status = 0;
+##################################################################################
 
-foreach ($output as $file) 
-{
-	// Check file hasn't been moved or deleted
-	if (!file_exists($file)) continue;
+# parse config
+CONFIG_FILE=$(dirname $0)/config
+if [ -e $CONFIG_FILE ]; then
+	. $CONFIG_FILE
+fi
 
-    // don't check files that aren't SCSS
-    if (!preg_match($filename_pattern, $file)) continue;
+# simple check if executable is set up correctly
+if [ ! -x $SL_BIN ]; then
+	echo "Scsslint bin not found or executable -> $SL_BIN"
+	exit 1
+fi
 
-    $lint_output = array();
-    exec("scss-lint -c $config " . escapeshellarg($file), $lint_output, $return);
-    if ($return == 0) {
-        continue;
-    }
+# stolen from template file
+if git rev-parse --verify HEAD
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
 
+# this is the magic: retrieve all files in staging area that
+# are added, modified or renamed but no deletions etc
+FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- )
 
-    echo 'scss-lint error: ' . implode("\n", $lint_output), "\n";
-    $exit_status = 1;
-}
+if [ "$FILES" == "" ]; then
+	exit 0
+fi
 
-exit($exit_status);
+# match files against whitelist
+FILES_TO_CHECK=""
+for FILE in $FILES
+do
+	echo "$FILE" | egrep -q "$SL_FILE_PATTERN"
+	RETVAL=$?
+	if [ "$RETVAL" -eq "0" ]
+	then
+		FILES_TO_CHECK="$FILES_TO_CHECK $FILE"
+	fi
+done
+
+if [ "$FILES_TO_CHECK" == "" ]; then
+	exit 0
+fi
+
+OUTPUT=$($SL_BIN $FILES_TO_CHECK)
+RETVAL=$?
+
+if [ $RETVAL -ne 0 ]; then
+	echo "$OUTPUT"
+fi
+
+exit $RETVAL
